resourceGroupName       = "Authentica-rg"
#resourceGroupNameShared = "mtech-databricks-terraform-dev"
location                = "East US 2" 
prefix                  = "authenctica"
suffix                  = "dev"
vnetRange               = ["10.100.4.0/23"]
publicSubnetRange       = ["10.100.4.0/24"]
privateSubnetRange      = ["10.100.5.0/24"]
sparkVersion            = "13.2.x-scala2.12"
de-vmSkuSize            = "Standard_DS3_v2"
ds-vmSkuSize            = "Standard_DS3_v2"
#single_user_name        = "evansadlon@mtech-systems.com"