name: Terraform Workflow

on: 
  workflow_dispatch:
    inputs:
      terraformconfig:
        description: 'Choose the Terraform command to run'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_LOG: DEBUG

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 0.14.3 # '1.2.3'

    - name: Terraform Init
      run: terraform init -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
                          -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
                          -backend-config="container_name=${{ secrets.AZURE_CONTAINER }}" \
                          -backend-config="key=${{ secrets.TFSTATE_FILE }}"
      working-directory: ./dev-environment

    - name: Terraform Plan
      if: ${{ github.event.inputs.terraformconfig == 'plan' || github.event.inputs.terraformconfig == 'apply' }}
      run: terraform plan -out=tfplan -lock=false -var-file="config.auto.tfvars"
      working-directory: ./dev-environment

    - name: Terraform Apply
      if: ${{ github.event.inputs.terraformconfig == 'apply' }}
      run: terraform apply "tfplan"
      working-directory: ./dev-environment

    - name: Terraform Destroy
      if: ${{ github.event.inputs.terraformconfig == 'destroy' }}
      run: terraform destroy -var-file="config.auto.tfvars"
      working-directory: ./dev-environment
